=== leydsonbarros/mule-sabor-express/src/main/resources/api/schemas/restaurantes/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Company": {
      "type": "string"
    },
    "Item": {
      "type": "string"
    },
    "price": {
      "type": "number"
    },
    "description": {
      "type": "string"
    }
  },
  "required": [
  
  ]
}

=== leydsonbarros/mule-sabor-express/src/main/resources/api/examples/restaurantes/response.json
[
   {
        "Company":"McDonald’s",
        "Item":"Hamburger",
        "price":32.42,
        "description":"Uma explosão de sabores em cada mordida."
    },
    {
        "Company":"McDonald’s",
        "Item":"Cheeseburger",
        "price":38.81,
        "description":"Uma opção saudável e equilibrada."
    },
    {
        "Company":"McDonald’s",
        "Item":"Double Cheeseburger",
        "price":50.18,
        "description":"Leve e saboroso, perfeito a qualquer hora."
    }
]
